# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test scenarios

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install locale
      run: |
        sudo locale-gen en_GB.UTF-8
        sudo locale-gen es_ES.UTF-8
        sudo update-locale LANG=en_GB.UTF-8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-playwright
        playwright install
        python -m pip install pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest and generate an HTML report
      run: |
        pytest --base-url https://www.saucedemo.com/v1/index.html --html=report.html

